### ISSUE TITLE
Custom made labels (labelGroup)

### ISSUE THREAD

**Issue by jprinsen** [sanity-io/demo-course-platform#29]
I do encounter certain malfunctioning whilst reproducing the labelGroup-approach. It may require some adjustment due to (a) how data is stored in LabelGroup itself and consequently, (b) being called upon by the groq in the queries.ts file (*_type* instead of _id ?):

```typescript
/* export const labelsQuery = groq`*[_id == "labelGroup"][0].labels[]{
  key,
  "text": coalesce(text[$language], text[$defaultLocale]),
}` */

export const labelsQuery = groq`*[_type == "labelGroup"][0].labels[]{
  key,
  "text": coalesce(text[$language], text[$defaultLocale]),
}`
``` 
May be worth an additional, fresh look to see whether the code requires some alterations.

![CleanShot 2023-07-04 at 12 28 48@2x](https://github.com/sanity-io/demo-course-platform/assets/24796548/126ee78a-72d0-4fc4-a7e8-8913eeb361a3)

**Comment by SimeonGriggs** [comment]
Studio does its best effort to pick a field to use as a title, but this particular schema type doesn't have a good one. I probably should just hard-code the list preview key for the schema type. Thanks for the message tho.
